In [3]:
import numpy as np
import pandas as pd
import torch
import os
import sys

In [2]:
from torchvision import datasets, transforms
import torch.utils.data as data

/home/juliu/anaconda3/envs/bach/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [40]:
df = pd.read_csv('data_analysis/val_imgs_df.csv')

In [80]:
df

file_name  multiple_objects  background  color  \
0      ILSVRC2012_val_00004487.JPEG                 0           1      0   
1      ILSVRC2012_val_00003963.JPEG                 0           1      1   
2      ILSVRC2012_val_00041992.JPEG                 0           0      1   
3      ILSVRC2012_val_00028056.JPEG                 0           1      0   
4      ILSVRC2012_val_00016832.JPEG                 0           0      1   
...                             ...               ...         ...    ...   
48863  ILSVRC2012_val_00004973.JPEG                 0           1      1   
48864  ILSVRC2012_val_00038750.JPEG                 0           1      0   
48865  ILSVRC2012_val_00043497.JPEG                 0           1      1   
48866  ILSVRC2012_val_00005859.JPEG                 0           1      0   
48867  ILSVRC2012_val_00005939.JPEG                 0           0      0   

       brighter  darker  style  larger  smaller  object_blocking  ...  \
0             0       0      0       1        0                0  ...   
1             0       0      1       0        0                0  ...   
2             0       0      0       0        0                0  ...   
3             0       0      0       0        0                0  ...   
4             0       1      0       0        0                0  ...   
...         ...     ...    ...     ...      ...              ...  ...   
48863         0       0      0       0        0                0  ...   
48864         0       0      1       0        0                0  ...   
48865         0       0      0       0        0                0  ...   
48866         0       0      0       0        0                0  ...   
48867         0       0      0       0        0                0  ...   

       partial_view  pattern  pose  shape  subcategory  texture  \
0                 0        0     1      0            0        0   
1                 0        0     1      0            0        0   
2                 0        0     1      0            0        0   
3                 0        1     1      1            0        0   
4                 0        0     1      0            0        0   
...             ...      ...   ...    ...          ...      ...   
48863             0        0     1      0            0        0   
48864             0        0     1      0            0        0   
48865             0        0     1      0            0        0   
48866             0        1     1      0            0        0   
48867             0        1     1      1            1        0   

                                           justification            one_word  \
0                     close up of a pan fried sea bass.    sea bass close up   
1                                   sepia image of tiger   digitally altered   
2                                    the bridge is brown           rare view   
3       the magnetic compass is on the bronze container           wood shape   
4                              A dark image of a church.                dark   
...                                                  ...                 ...   
48863                                 color is different               color   
48864  front view image of rocking chair made by digi...  window digital art   
48865  right angle of analog clock with gold metallic...         right angle   
48866                A different design of a beer glass.  pattern background   
48867                        a different types of corals              corals   

      label         str_label  
0       762        restaurant  
1       292             tiger  
2       718              pier  
3       635  magnetic compass  
4       497            church  
...     ...               ...  
48863   973        coral reef  
48864   765     rocking chair  
48865   409      analog clock  
48866   441        beer glass  
48867   973        coral reef  

[48868 rows x 21 columns]

In [49]:
class MultiLabel(datasets.ImageFolder):
    def __init__(self, type_str, folder_path, annotations_path, *args, **kwargs):
        self.type = type_str
        super().__init__(folder_path + self.type, *args, **kwargs)
        if self.type == "val":
            self.label_df = pd.read_json(
                annotations_path + "imagenet_x_" + "train" + "_multi_factor.jsonl",
                lines=True,
            )
        if self.type == "train":
            self.label_df = pd.read_json(
                annotations_path + "imagenet_x_" + "val" + "_multi_factor.jsonl",
                lines=True,
            )

    # multilabel getitem method:
    def __getitem__(self, index: int):
        path, target = self.samples[index]
        sample = self.loader(path)

        if self.transform is not None:
            sample = self.transform(sample)

        # overwrite multilabel target:
        if self.type == "val":
            target = self.label_df[self.label_df.file_name == path[-20:]].values[0][2:18]

        if self.type == "train":
            target = self.label_df[self.label_df.file_name == path[-28:]].values[0][2:18]
        return sample, target

[0 1 1 0 0 0 0 0 0 0 0 1 1 1 0 1]


In [37]:
MultiLabel('train', )

[]


array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=object)

In [81]:
x, y = train_data.__getitem__(4)

In [82]:
y

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=object)

In [63]:
arr = df[df.file_name == x[-28:]].values[0][1:17]

In [69]:
arr

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=object)